"""initial_schema

Revision ID: 915daa30f816
Revises: 
Create Date: 2026-09-10 18:49:10.159111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '915daa30f816'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercise_executions', sa.Column('rpe', sa.Float(), nullable=True))
    op.add_column('exercise_executions', sa.Column('rir', sa.Float(), nullable=True))
    op.add_column('exercise_executions', sa.Column('e1rm', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercise_executions', 'e1rm')
    op.drop_column('exercise_executions', 'rir')
    op.drop_column('exercise_executions', 'rpe')
    # ### end Alembic commands ###
